### ISSUE TITLE
MyData fails to upload data of a MyTardis user whose name is listed after a non-MyTardis user

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mydata#25]
_From @iiman on November 10, 2015 3:11_

Hi,

I will use a scenario to explain the issue.

Given:
- DATA_DIRECTORY is a path to datasets
- MyData is configured to have a folder structure of "Username/Dataset". This folder structure resides under $DATA_DIRECTORY
- The users that are listed under $DATA_DIRECTORY are James, Martha, Peter and Richard.
- James, Martha and Richard are MyTardis users but Peter is not.

Result:
- MyData will upload datasets of James and Martha. But it will not upload Richard's datasets. This is because MyData stops uploading as soon as it finds a non-MyTardis user, which is Peter in this scenario. 

Suggestion:
MyData should ignore non-MyTardis users and continue uploading datasets of MyTardis users. This is important especially if $DATA_DIRECTORY is a network drive that is accessed by both MyTardis and non-MyTardis users.

Cheers,

_Copied from original issue: wettenhj/mytardis-app-mydata#3_

**Comment by wettenhj** [comment]
@iiman, thanks for reporting this.  This is a bug which needs fixing ASAP - MyData should not stop uploading just because it comes across a user folder which it can't match to a MyTardis user account.

However, not everyone would agree that "MyData should ignore non-MyTardis users...".  If a user labels their folder incorrectly, some facilities would prefer to have MyData upload the data but only make it accessible to the facility administrators until the user account has been created in MyTardis.  So this is the behaviour we have tried to achieve with MyData (but it appears to be broken at present).

**Comment by iiman** [comment]
@wettenhj, I actually think it is a good idea to upload the data despite MyData not being able to match the user to a MyTardis account. Like you said, there might be a simple configuration issue like typo, ...

However, what MyData should not do is stop uploading when it finds a user whose MyTardis account cannot be retrieved.

Cheers

**Comment by wettenhj** [comment]
After moving this issue from the mytardis-app-mydata repo to the mydata repo, I realized that this was actually an issue with mytardis-app-mydata (MyData's server-side MyTardis app), so I'll close this issue and reopen the mytardis-app-mydata issue.
