### ISSUE TITLE
Remove "MyTardis" from "MyTardis Sync" menu item in MyData taskbar menu

### ISSUE THREAD

**Issue by keithschulze** [mytardis/mydata#34]
MyData's task bar menu currently has a "MyTardis Sync" menu item to kick off data sync. Feedback suggests that MyTardis branding might be confusing since deployments may not include that name (e.g. Store.Monash). Perhaps the menu item could simply be  "Sync".

**Comment by wettenhj** [comment]
Addressed in v0.5.1
