### ISSUE TITLE
Large files with filenames containing '$' fail to upload when using SCP via Staging upload method.

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mydata#35]
When using its SCP via Staging upload method, MyData breaks up large files into chunks.
For a file named "file1.dat", MyData does the following:
1. Extract chunk
2. Upload chunk to staging area, naming it ".file1.dat.chunk"
3. Append chunk to partial upload: ssh staging_host "cat .file1.dat.chunk >> \"file1.dat\""

This can fail for filenames containing '$' symbols, because the remote shell will try to evaluate the '$' in the string.

For small files, MyData simply SCPs the entire file in one step (without incremental progress updates or the ability to resume partial uploads).  Recent testing shows that MyData's small file uploads are not affected by this issue.

**Comment by jasonrig** [comment]
Can you try enclosing your command parameters (e.g. file names) with single quotes? This should stop the shell from interpreting dollar signs.

**Comment by pansapiens** [comment]
Would there also be a problem if a user named their file something similar to: 

`file1.$(find /all/my/data -name "*" -delete).dat`

Do you need to consider using pipes.quote() here ? (or shelx.quote() for Python 3)

**Comment by wettenhj** [comment]
@jasonrig, yes I have considered single quotes, but that makes filenames containing apostrophes painful to deal with.  

How would you quote something like this?

ssh remotehost "echo 'Jason's test filename.txt' "

Backslashes around the internal apostrophe won't help you here - you'd need to do something like this:

ssh remotehost "echo 'Jason'\"'\"'s test filename.txt' "

I haven't ruled out switching to single-quote quoting, but I don't like the inability to escape internal apostrophes in a "normal" way (e.g. with a backslash before the internal apostrophe).  And obviously a change like this would need to be thoroughly tested across different client OS's - there are some weird OS-specific quoting issues when running remote commands via SSH.

**Comment by wettenhj** [comment]
@pansapiens, there are easier ways to maliciously use MyData's SSH key-pair to mess with the staging area, so it's always important to ensure that the "mydata" SCP account is unprivileged and doesn't have write access to the permanent MyTardis storage boxes, only to a staging area.  Ideally there should be multiple "mydata" SCP accounts for a MyTardis service, e.g. one per facility, or even one per instrument, so that the risk of someone using MyData's SSH key-pair maliciously is contained.

Yes, pipes.quote() could help in this case - but would need cross-platform testing.

Or maybe it's time to go full circle back to Paramiko!  I'm not sure if you know the history, but in early versions of our client-side GUIs (Launcher/Strudel etc.), we used Python's Paramiko SSH module to run remote commands, then we switched to using SSH/SCP subprocesses for various reasons, but it can certainly lead to some painful quoting issues.  However one nice thing about using external SSH/SCP binaries is being able to easily switch between different SSH builds (e.g. those with HPN patches).

Or we could request a solution on the MyTardis server side, i.e. when uploading to a temporary URL, MyData could say "Please, MyTardis, just give me a simple directory and filename to upload to for the staged datafile, e.g. staging_dir/[dataset_id]/[uuid], then the client wouldn't have to worry about special characters in dataset names, subdirectory names or filenames.  In MyTardis 3.5, the staging directory to upload to used a UUID and the dataset directory was just a number (dataset ID) so it wouldn't matter if there were special characters in the dataset description.  However I think the real filename was still used, not a UUID replacement: https://github.com/mytardis/mytardis/blob/3.5/tardis/tardis_portal/staging.py#L175

I actually think that (after uploading years worth of flow cytometry data), we are finally approaching the end of these painful "special character" in dataset name / subdirectory name / filename issues!

**Comment by wettenhj** [comment]
@jasonrig, I should clarify that regarding single quoting, whilst I don't like the idea of having to deal with internal apostrophes within a single-quoted string myself, I'm happy to use an existing Python library which does this - and @pansapiens's suggestion of use pipes.quote probably does exactly this.

**Comment by wettenhj** [comment]
Fixed in https://github.com/mytardis/mydata/commit/e7dc1217ad7a75cceee587ae0d53c27660507d62
