### ISSUE TITLE
Allow use of self-signed certs for mytardis

### ISSUE THREAD

**Issue by ianedwardthomas** [mytardis/mydata#52]
There should be an option to allow mydata to connect to a mytardis that  has ssl enabled but only uses self-signed certificates.  Currently it fails with certificate_verify_failed.

**Comment by wettenhj** [comment]
Have you tried adding your certificate to the cacert.pem file bundled with MyData?

Or you can set the REQUESTS_CA_BUNDLE environment variable to point to a different location for cacert.pem.

**Comment by ianedwardthomas** [comment]
That first solution appears to have worked.  Cheers.
