### ISSUE TITLE
Duplicate experiments on first scan and upload in MyData

### ISSUE THREAD

**Issue by RichardPBerry** [mytardis/mydata#93]
When using MyData to upload a new Experiment and Dataset it leads to duplicate Experiments in MyTardis.

The first time the MyData client is run with multiple folders (datasets) to a single experiment using the MyData client in  "User Group / Experiment / Dataset" mode, a new experiment for EACH data set is created, rather than a single Experiment with multiple datasets. So, for example, a folder structure of:
- Group_name
  - Experiment A
    - Dataset 1A
    - Dataset 1B
    - Dataset 1C

results in three experiments in MyTardis all named Group_name - Experiment A. Example of duplicate datasets: ![example duplicate datasets](https://cloud.githubusercontent.com/assets/22140635/21169230/8abcdc96-c20e-11e6-8584-7fb2f61a395d.png)

The second time the MyData client is run (without making any changes, just click run again) all three are correctly mapped to one of the Experiments only. So in the above example one of the three experiments created in the first run will now contain 3 datasets (i.e. the expected behaviour).

Running a third time time correctly detects that there are no new files.

I found the problem running the mac version of the client and was able to replicate similar problems with the windows version on another machine.

It seems that adding a new folder/dataset to an existing experiment that MyData already knows about does not create duplicate experiments - so the problem only seems to happen if the first scan of a new Experiment level folder contains multiple subfolders at dataset level.

**Comment by wettenhj** [comment]
Thanks for reporting.  Which version of MyData are you using?

This should be fixed in v0.6.3-beta and v0.7.0-beta.

Maybe try: https://github.com/mytardis/mydata/releases/tag/v0.6.3-beta3

**Comment by RichardPBerry** [comment]
Ahh, ok I was using 0.6.2. I just tried the beta and it looked like it worked fine.

**Comment by wettenhj** [comment]
Great, thanks for letting us know.

**Comment by wettenhj** [comment]
Fixed in v0.6.3 and later.
